### ISSUE TITLE
editing lat and lon, cursor jumped to end

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax-ui#38]
Trying to change,  say 71.456 to 72.456,  on lat or lon fields, parked the cursor befor '.', then hit the "<-<--back space" key, the cursor jumped to the end. 
snap revision 75, on rpi3.

**Comment by bmpotter** [comment]
Varatep, when you fixed the similar problem in the email field, did you not check all fields that have verification? Or is this a different problem?

**Comment by varatep** [comment]
@bmpotter I will take a look at these fields, the email field was a part of the initial registration page and that was what I looked at.

**Comment by bmpotter** [comment]
Varatep, when you are fixing a reported bug, you should always search the code to make sure similar bugs don't exist elsewhere.

**Comment by varatep** [comment]
Related to: https://github.com/facebook/react/pull/8204
There is a temporary fix for less-accurate numbers (up to 14 decimal places i.e. `-118.3321553213131311`) where the text field will not reset. Will commit and then look at other text fields for a temporary fix as well.

React v16 should fix this with reconciliation flushing order.

**Comment by varatep** [comment]
Track here: https://github.com/varatep/anax-ui/tree/bug/cursor-jumps-to-end

**Comment by linggao** [comment]
Still not working for LAT and LON. Every time I deleted a character the cursor jumped to the end after the deletion.

**Comment by varatep** [comment]
@linggao I'm going to need to update to the latest `React.js v16`, which will take some effort as there are dependencies of `v15` that break. I will be branching off and trying to update to the latest version this week.
